services:
  segmenter:
    model_path: 'models/onnx_model/onnx_model.onnx'
    device: 'cpu'
    ort_provider: 'CPUExecutionProvider'
    img_input_size: 256
    threshold_prob: 0.4
    threshold_size: 30
  ocr:
    model_path: 'models/ts_script_model/final_ocr.pt'
    device: 'cpu'
    width: 416
    height: 96
    vocab: '0123456789'
